### ISSUE TITLE
Reconnected local peer is an unknown peer

### ISSUE THREAD

**Issue by kevireilly** [tristanls/gossipmonger#6]
When a peer gets disconnected from the cluster and reconnects, the local peer starts emitting the `unknown peer` event after receiving `deltas` from a remote peer since itself is not in `storage`. Wondering `if (id === self.localPeer.id) return;` might be a reasonable way to handle this scenario instead.

**Comment by tristanls** [comment]
That seems reasonable.

I wonder what sequence of events results in a node receiving outdated deltas about itself from a remote peer?

In order to emit `unknown peer` the following needs to be true (_I think_):
- `self.localPeer` is not in `storage`
- receive `delta` from remote peer about `self.localPeer`
- remote peer must send `delta` about `self.localPeer` to `self.localPeer`
- remote peer sends `delta` about `self.localPeer` [only if `$(remote).$(localPeer).maxVersionSeen > self.localPeer.maxVersionSeen`](https://github.com/tristanls/gossipmonger/blob/794d845145f7fa0f22a17793ab44938c2604a046/index.js#L197)
- remote peer must receive `digest` from `self.localPeer` (`delta`s are only sent in response to `digest`s)
- `digestToSend` must contain `self.localPeer`
- When `digestToSend` is created, [it has `self.localPeer.maxVersionSeen` included that is less than `$(remote).$(localPeer).maxVersionSeen`](https://github.com/tristanls/gossipmonger/blob/794d845145f7fa0f22a17793ab44938c2604a046/index.js#L282) (this seems problematic, as this should not be happening)
- `self.localPeer.maxVersionSeen` is [initiated with zero on creation](https://github.com/tristanls/gossipmonger/blob/794d845145f7fa0f22a17793ab44938c2604a046/index.js#L78)
- `self.localPeer.maxVersionSeen` is [monotonically incremented by `updateLocal`](https://github.com/tristanls/gossipmonger-peer/blob/bd649e122ff6a3685f739b0e764fac0b7fe09d80/index.js#L213) when [update is called](https://github.com/tristanls/gossipmonger/blob/794d845145f7fa0f22a17793ab44938c2604a046/index.js#L360); so somehow `self.localPeer.maxVersionSeen` is decremented out of band?

_If the assertions above are true_, then to observe what you're describing, the local peer, when it gets disconnected, would have to keep the same `id`, while resetting its own `maxVersionSeen` to `0`. Is that what is happening? (If yes, I would recommend not resetting `maxVersionSeen` to `0`).

**Comment by kevireilly** [comment]
You nailed it! The `maxVersionSeen` was being reset due to hot reloads alongside a statically defined ID and I'm wishing I had provided more context. One solution appears to be retaining the previous version after `GossipMongerInstance.update` is called and passing it in on future instantiations. 

Any downside to taking that approach especially for potentially long durations of being away from the cluster? Alternatively, suppose a unique `id` could be used each time. Really appreciate the detailed response as it provided some excellent insight in to what is going on under the hood. Super fun stuff.

**Comment by tristanls** [comment]
Oh wow!, that was a long shot.. haha 😄.

If I understand correctly, yes, retaining the previous version and passing it to future instantiations should work when the `id` is retained across hot reloads. This has the benefit of having less total peers to track in the network, therefore less communication attempts to dead peers, less state to track, etc. I'd recommend this approach.

Similarly, generating a new `id` each time would also work. Downside is that this would result in tracking more peers.

Cheers!

**Comment by kevireilly** [comment]
Makes a ton of sense indeed, thanks again for the insight and assistance.
